# 4.5 데이터프레임 인덱스 조작

## 데이터프레임 인덱스 설정 및 제거

때로는 데이터프레임에 인덱스로 들어가 있어야 할 데이터가 일반 데이터 열에 들어가 있거나   
반대로 일반 데이터 열이어야 할 것이 인덱스로 되어 있을 수 있다.   
이 때는 `set_index` 명령이나 `reset_index` 명령으로 인덱스와 일반 데이터 열을 교환할 수 있다.

* `set_index` : 기존의 행 인덱스를 제거하고 데이터 열 중 하나를 인덱스로 설정
* `reset_index` : 기존의 행 인덱스를 제거하고 인덱스를 데이터 열로 추가

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.round(np.random.rand(3, 5), 2)

array([[0.97, 0.59, 0.22, 0.1 , 0.02],
       [0.54, 0.56, 0.55, 0.99, 0.54],
       [0.01, 0.07, 0.82, 0.39, 0.99]])

In [3]:
np.vstack([list('ABCDE'), np.round(np.random.rand(3, 5), 2)])

array([['A', 'B', 'C', 'D', 'E'],
       ['0.52', '0.67', '0.49', '0.46', '0.93'],
       ['0.38', '0.33', '0.85', '0.84', '0.0'],
       ['0.35', '0.0', '0.53', '0.96', '0.97']], dtype='<U32')

In [4]:
np.random.seed(0)
df1 = pd.DataFrame(np.vstack([list('ABCDE'), np.round(np.random.rand(3, 5), 2)]).T, # transpose
                   columns=["C1", "C2", "C3", "C4"])
df1

C1    C2    C3    C4
0  A  0.55  0.65  0.79
1  B  0.72  0.44  0.53
2  C   0.6  0.89  0.57
3  D  0.54  0.96  0.93
4  E  0.42  0.38  0.07

```{margin}
`set_index`
```

`set_index` 메서드로 특정한 열을 인덱스로 설정할 수 있다. 이 때 기존의 인덱스는 없어진다.

In [6]:
df2 = df1.set_index("C1")
df2

C2    C3    C4
C1                  
A   0.55  0.65  0.79
B   0.72  0.44  0.53
C    0.6  0.89  0.57
D   0.54  0.96  0.93
E   0.42  0.38  0.07

마찬가지로 C2열을 인덱스로 지정하면 기존의 인덱스는 사라진다.

In [7]:
df2.set_index("C2") # 원본 반영 안됨

C3    C4
C2              
0.55  0.65  0.79
0.72  0.44  0.53
0.6   0.89  0.57
0.54  0.96  0.93
0.42  0.38  0.07

In [8]:
df2

C2    C3    C4
C1                  
A   0.55  0.65  0.79
B   0.72  0.44  0.53
C    0.6  0.89  0.57
D   0.54  0.96  0.93
E   0.42  0.38  0.07

```{margin}
`reset_index`
```

반대로 `reset_index` 메서드를 쓰면 인덱스를 보통의 자료열로 바꿀 수도 있다.    
이 때 인덱스 열은 자료열의 가장 선두로 삽입된다.    
데이터프레임의 인덱스는 정수로 된 디폴트 인덱스로 바뀐다.

In [9]:
df2.reset_index()

C1    C2    C3    C4
0  A  0.55  0.65  0.79
1  B  0.72  0.44  0.53
2  C   0.6  0.89  0.57
3  D  0.54  0.96  0.93
4  E  0.42  0.38  0.07

In [10]:
df2

C2    C3    C4
C1                  
A   0.55  0.65  0.79
B   0.72  0.44  0.53
C    0.6  0.89  0.57
D   0.54  0.96  0.93
E   0.42  0.38  0.07

`reset_index` 메서드를 호출할 때 인수 `drop=True` 로 설정하면 인덱스 열을 보통의 자료열로 올리는 것이 아니라 그냥 버리게 된다.

In [11]:
df2.reset_index(drop=True)

C2    C3    C4
0  0.55  0.65  0.79
1  0.72  0.44  0.53
2   0.6  0.89  0.57
3  0.54  0.96  0.93
4  0.42  0.38  0.07

### 연습 문제
```
5명의 학생의 국어, 영어, 수학 점수를 나타내는 데이터프레임을 다음과 같이 만든다.

1. 학생 이름을 나타내는 열을 포함시키지 않고 데이터프레임 `df_score1` 을 생성한 후,   
`df_score1.index` 속성에 학생 이름을 나타내는 열을 지정하여 인덱스를 지정한다.    
`reset_index` 명령으로 이 인덱스 열을 명령으로 일반 데이터열로 바꾸여 데이터프레임 `df_score2`을 만든다.
2. 학생 이름을 나타내는 열이 일반 데이터 열을 포함하는 데이터프레임 `df_score2`에 `set_index` 명령을 적용하여 다시 학생 이름을 나타내는 열을 인덱스로 변경한다.
```

In [14]:
df_score1=pd.DataFrame(np.random.randint(0,101, size=(5,3)), columns=['국어', '영어', '수학'])
df_score1

국어  영어  수학
0  35  11  46
1  82  91   0
2  14  99  53
3  12  42  84
4  75  68   6

In [18]:
df_score1.index = ['학생1', '학생2', '학생3', '학생4', '학생5']
df_score1

국어  영어  수학
학생1  35  11  46
학생2  82  91   0
학생3  14  99  53
학생4  12  42  84
학생5  75  68   6

In [12]:
# 데이터 프레임 생성
df_score1 = pd.DataFrame(np.random.randint(0, 101, size=(5, 3)), columns=['국어', '영어', '수학'])
df_score1

국어  영어  수학
0   9  20  80
1  69  79  47
2  64  82  99
3  88  49  29
4  19  19  14

In [13]:
# 인덱스에 학생 이름 지정
df_score1.index = ['학생1', '학생2', '학생3', '학생4', '학생5']
df_score1

국어  영어  수학
학생1   9  20  80
학생2  69  79  47
학생3  64  82  99
학생4  88  49  29
학생5  19  19  14

In [14]:
# 인덱스 열을 일반 데이터열로 바꾸어 데이터프레임 생성
df_score2 = df_score1.reset_index()
df_score2

index  국어  영어  수학
0   학생1   9  20  80
1   학생2  69  79  47
2   학생3  64  82  99
3   학생4  88  49  29
4   학생5  19  19  14

In [15]:
# 학생 이름을 다시 인덱스로 변경
df_score2 = df_score2.set_index('index')
df_score2

국어  영어  수학
index            
학생1     9  20  80
학생2    69  79  47
학생3    64  82  99
학생4    88  49  29
학생5    19  19  14

## 다중 인덱스

```{margin}
다중 인덱스(multi-index)
```

행이나 열에 여러 계층을 가지는 인덱스 즉, 다중 인덱스(multi-index)를 설정할 수도 있다.   
데이터프레임을 생성할 때 `columns` 인수에 다음 예제처럼 리스트의 리스트(행렬) 형태로 인덱스를 넣으면 다중 열 인덱스를 가지게 된다.

In [16]:
np.random.seed(0)
df3 = pd.DataFrame(np.round(np.random.randn(5, 4), 2),
                   columns=[["A", "A", "B", "B"],
                            ["C1", "C2", "C1", "C2"]])
df3

A           B      
     C1    C2    C1    C2
0  1.76  0.40  0.98  2.24
1  1.87 -0.98  0.95 -0.15
2 -0.10  0.41  0.14  1.45
3  0.76  0.12  0.44  0.33
4  1.49 -0.21  0.31 -0.85

```{margin}
`columns.names`
```

다중 인덱스는 이름을 지정하면 더 편리하게 사용할 수 있다. 열 인덱스들의 이름 지정은 `columns` 객체의 `names` 속성에 리스트를 넣어서 지정한다.

In [17]:
df3.columns.names = ["Cidx1", "Cidx2"]
df3

Cidx1     A           B      
Cidx2    C1    C2    C1    C2
0      1.76  0.40  0.98  2.24
1      1.87 -0.98  0.95 -0.15
2     -0.10  0.41  0.14  1.45
3      0.76  0.12  0.44  0.33
4      1.49 -0.21  0.31 -0.85

```{margin}
`index.names`
```

마찬가지로 데이터프레임을 생성할 때 `index` 인수에 리스트의 리스트(행렬) 형태로 인덱스를 넣으면 다중 (행) 인덱스를 가진다.   
행 인덱스들의 이름 지정은 `index` 객체의 `names` 속성에 리스트를 넣어서 지정한다.

In [20]:
np.random.seed(0)
df4 = pd.DataFrame(np.round(np.random.randn(6, 4), 2),
                   columns=[["A", "A", "B", "B"],
                            ["C", "D", "C", "D"]],
                   index=[["M", "M", "M", "F", "F", "F"],
                          ["id_" + str(i + 1) for i in range(3)] * 2])
df4.columns.names = ["Cidx1", "Cidx2"]
df4.index.names = ["Ridx1", "Ridx2"]
df4

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx1 Ridx2                        
M     id_1   1.76  0.40  0.98  2.24
      id_2   1.87 -0.98  0.95 -0.15
      id_3  -0.10  0.41  0.14  1.45
F     id_1   0.76  0.12  0.44  0.33
      id_2   1.49 -0.21  0.31 -0.85
      id_3  -2.55  0.65  0.86 -0.74

## 행 인덱스와 열 인덱스 교환

```{margin}
`stack`
```

```{margin}
`unstack`
```

`stack` 메서드나 `unstack` 메서드를 쓰면 열 인덱스를 행 인덱스로 바꾸거나 반대로 행 인덱스를 열 인덱스로 바꿀 수 있다.

* `stack`
 * 열 인덱스 -> 행 인덱스로 변환

* `unstack`
 * 행 인덱스 -> 열 인덱스로 변환

`stack` 메서드를 실행하면 열 인덱스가 반시계 방향으로 90도 회전한 것과 비슷한 모양이 된다.   
마찬가지로 `unstack` 메서드를 실행하면 행 인덱스가 시계 방향으로 90도 회전한 것과 비슷하다.   
인덱스를 지정할 때는 문자열 이름과 순서를 표시하는 숫자 인덱스를 모두 사용할 수 있다.

In [21]:
df4

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx1 Ridx2                        
M     id_1   1.76  0.40  0.98  2.24
      id_2   1.87 -0.98  0.95 -0.15
      id_3  -0.10  0.41  0.14  1.45
F     id_1   0.76  0.12  0.44  0.33
      id_2   1.49 -0.21  0.31 -0.85
      id_3  -2.55  0.65  0.86 -0.74

In [29]:
df4.stack("Cidx1") # 열인덱스->행인덱스

Cidx2                 C     D
Ridx1 Ridx2 Cidx1            
M     id_1  A      1.76  0.40
            B      0.98  2.24
      id_2  A      1.87 -0.98
            B      0.95 -0.15
      id_3  A     -0.10  0.41
            B      0.14  1.45
F     id_1  A      0.76  0.12
            B      0.44  0.33
      id_2  A      1.49 -0.21
            B      0.31 -0.85
      id_3  A     -2.55  0.65
            B      0.86 -0.74

In [23]:
df4.stack?

Signature:
df4.stack(
    level: 'IndexLabel' = -1,
    dropna: 'bool | lib.NoDefault' = <no_default>,
    sort: 'bool | lib.NoDefault' = <no_default>,
    future_stack: 'bool' = False,
)
Docstring:
Stack the prescribed level(s) from columns to index.

Return a reshaped DataFrame or Series having a multi-level
index with one or more new inner-most levels compared to the current
DataFrame. The new inner-most levels are created by pivoting the
columns of the current dataframe:

  - if the columns have a single level, the output is a Series;
  - if the columns have multiple levels, the new index
    level(s) is (are) taken from the prescribed level(s) and
    the output is a DataFrame.

Parameters
----------
level : int, str, list, default -1
    Level(s) to stack from the column axis onto the index
    axis, defined as one index or label, or a list of indices
    or labels.
dropna : bool, default True
    Whether to drop rows in the resulting Frame/Series with
    missing values. Stackin

In [33]:
df4.stack(-1) # cidx2 == 1

Cidx1                 A     B
Ridx1 Ridx2 Cidx2            
M     id_1  C      1.76  0.98
            D      0.40  2.24
      id_2  C      1.87  0.95
            D     -0.98 -0.15
      id_3  C     -0.10  0.14
            D      0.41  1.45
F     id_1  C      0.76  0.44
            D      0.12  0.33
      id_2  C      1.49  0.31
            D     -0.21 -0.85
      id_3  C     -2.55  0.86
            D      0.65 -0.74

In [24]:
df4.stack(0) # cidx2 == 1

Cidx2                 C     D
Ridx1 Ridx2 Cidx1            
M     id_1  A      1.76  0.40
            B      0.98  2.24
      id_2  A      1.87 -0.98
            B      0.95 -0.15
      id_3  A     -0.10  0.41
            B      0.14  1.45
F     id_1  A      0.76  0.12
            B      0.44  0.33
      id_2  A      1.49 -0.21
            B      0.31 -0.85
      id_3  A     -2.55  0.65
            B      0.86 -0.74

In [25]:
df4.unstack("Ridx2")

Cidx1     A                                   B                              
Cidx2     C                 D                 C                 D            
Ridx2  id_1  id_2  id_3  id_1  id_2  id_3  id_1  id_2  id_3  id_1  id_2  id_3
Ridx1                                                                        
F      0.76  1.49 -2.55  0.12 -0.21  0.65  0.44  0.31  0.86  0.33 -0.85 -0.74
M      1.76  1.87 -0.10  0.40 -0.98  0.41  0.98  0.95  0.14  2.24 -0.15  1.45

In [26]:
df4

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx1 Ridx2                        
M     id_1   1.76  0.40  0.98  2.24
      id_2   1.87 -0.98  0.95 -0.15
      id_3  -0.10  0.41  0.14  1.45
F     id_1   0.76  0.12  0.44  0.33
      id_2   1.49 -0.21  0.31 -0.85
      id_3  -2.55  0.65  0.86 -0.74

In [27]:
 df4.unstack(0) # ridx1 == 0

Cidx1     A                       B                  
Cidx2     C           D           C           D      
Ridx1     F     M     F     M     F     M     F     M
Ridx2                                                
id_1   0.76  1.76  0.12  0.40  0.44  0.98  0.33  2.24
id_2   1.49  1.87 -0.21 -0.98  0.31  0.95 -0.85 -0.15
id_3  -2.55 -0.10  0.65  0.41  0.86  0.14 -0.74  1.45

## 다중 인덱스가 있는 경우의 인덱싱과 슬라이싱

데이터프레임이 다중 인덱스를 가지는 경우에는 인덱스 값이 하나의 라벨이나 숫자가 아니라 `()`로 둘러싸인 튜플이 되어야 한다.    
예를 들어 앞에서 만든 `df3` 데이터프레임의 경우 다음과 같이 인덱싱할 수 있다.

In [28]:
df3

Cidx1     A           B      
Cidx2    C1    C2    C1    C2
0      1.76  0.40  0.98  2.24
1      1.87 -0.98  0.95 -0.15
2     -0.10  0.41  0.14  1.45
3      0.76  0.12  0.44  0.33
4      1.49 -0.21  0.31 -0.85

In [29]:
df3[ ("B", "C1") ]

0    0.98
1    0.95
2    0.14
3    0.44
4    0.31
Name: (B, C1), dtype: float64

`loc` 인덱스를 사용하는 경우에도 마찬가지로 튜플을 써야 한다.

In [30]:
df3.loc[0, ("B", "C1")]

0.98

In [31]:
df3.loc[0, ("B", "C1")] = 100
df3

Cidx1     A             B      
Cidx2    C1    C2      C1    C2
0      1.76  0.40  100.00  2.24
1      1.87 -0.98    0.95 -0.15
2     -0.10  0.41    0.14  1.45
3      0.76  0.12    0.44  0.33
4      1.49 -0.21    0.31 -0.85

단, `iloc` 인덱서를 사용하는 경우에는 튜플 형태의 다중인덱스를 사용할 수 없다.

In [32]:
df3.iloc[0, 2]

100.0

만약 하나의 레벨 값만 넣으면 다중 인덱스 중에서 가장 상위의 값을 지정한 것으로 본다.

In [34]:
df3['A']

Cidx2    C1    C2
0      1.76  0.40
1      1.87 -0.98
2     -0.10  0.41
3      0.76  0.12
4      1.49 -0.21

In [35]:
# 당연히 하위 인덱스는 단일 라벨값만 넣으면 인식이 안된다.
df3['C1']

KeyError: 'C1'

`df4` 데이터프레임은 다음과 같이 인덱싱할 수 있다.

In [36]:
df4

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx1 Ridx2                        
M     id_1   1.76  0.40  0.98  2.24
      id_2   1.87 -0.98  0.95 -0.15
      id_3  -0.10  0.41  0.14  1.45
F     id_1   0.76  0.12  0.44  0.33
      id_2   1.49 -0.21  0.31 -0.85
      id_3  -2.55  0.65  0.86 -0.74

In [37]:
df4.loc[("M", "id_1"), ("A", "C")]

1.76

In [37]:
df4.loc[:, ("A", "C")]

Ridx1  Ridx2
M      id_1     1.76
       id_2     1.87
       id_3    -0.10
F      id_1     0.76
       id_2     1.49
       id_3    -2.55
Name: (A, C), dtype: float64

In [38]:
df4.loc[("M", "id_1"), :]

Cidx1  Cidx2
A      C        1.76
       D        0.40
B      C        0.98
       D        2.24
Name: (M, id_1), dtype: float64

In [39]:
df4.loc[("All", "All"), :] = df4.sum()
df4

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx1 Ridx2                        
M     id_1   1.76  0.40  0.98  2.24
      id_2   1.87 -0.98  0.95 -0.15
      id_3  -0.10  0.41  0.14  1.45
F     id_1   0.76  0.12  0.44  0.33
      id_2   1.49 -0.21  0.31 -0.85
      id_3  -2.55  0.65  0.86 -0.74
All   All    3.23  0.39  3.68  2.28

`loc`를 사용하는 경우에도 튜플이 아닌 하나의 값만 쓰면 가장 상위의 인덱스를 지정한 것과 같다.

In [40]:
df4.loc["M"]

Cidx1     A           B      
Cidx2     C     D     C     D
Ridx2                        
id_1   1.76  0.40  0.98  2.24
id_2   1.87 -0.98  0.95 -0.15
id_3  -0.10  0.41  0.14  1.45

```{margin}
`slice(None)`
```

특정 레벨의 모든 인덱스 값을 인덱싱할 때는 슬라이스를 사용한다.   
다만 다중 인덱스의 튜플 내에서는 `:` 슬라이스 기호를 사용할 수 없고 대신 `slice(None)` 값을 사용해야 한다.

In [44]:
df4.loc[("M": ), :]

SyntaxError: invalid syntax (<ipython-input-44-ca3dce916118>, line 1)

In [45]:
df4.loc[("M", slice(None)), :] # ("M" : ) -> 불가 

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx1 Ridx2                        
M     id_1   1.76  0.40  0.98  2.24
      id_2   1.87 -0.98  0.95 -0.15
      id_3  -0.10  0.41  0.14  1.45

In [43]:
df4.loc[(slice(None), "id_1"), :]

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx1 Ridx2                        
M     id_1   1.76  0.40  0.98  2.24
F     id_1   0.76  0.12  0.44  0.33

## 다중 인덱스의 인덱스 순서 교환

다중 인덱스의 인덱스 순서를 바꾸고 싶으면 `swaplevel` 명령을 사용한다.

* `swaplevel(i, j, axis)`

`i`와 `j`는 교환하고자 하는 인덱스 라벨(혹은 인덱스 번호)이고 `axis`는 0일 때 행 인덱스, 1일 때 열 인덱스를 뜻한다. 디폴트는 행 인덱스이다.

In [34]:
df4

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx1 Ridx2                        
M     id_1   1.76  0.40  0.98  2.24
      id_2   1.87 -0.98  0.95 -0.15
      id_3  -0.10  0.41  0.14  1.45
F     id_1   0.76  0.12  0.44  0.33
      id_2   1.49 -0.21  0.31 -0.85
      id_3  -2.55  0.65  0.86 -0.74

In [35]:
df5 = df4.swaplevel("Ridx1", "Ridx2") # 디폴트 0
df5

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx2 Ridx1                        
id_1  M      1.76  0.40  0.98  2.24
id_2  M      1.87 -0.98  0.95 -0.15
id_3  M     -0.10  0.41  0.14  1.45
id_1  F      0.76  0.12  0.44  0.33
id_2  F      1.49 -0.21  0.31 -0.85
id_3  F     -2.55  0.65  0.86 -0.74

In [37]:
df6 = df4.swaplevel("Cidx1", "Cidx2", 1) # axis=1
df6

Cidx2           C     D     C     D
Cidx1           A     A     B     B
Ridx1 Ridx2                        
M     id_1   1.76  0.40  0.98  2.24
      id_2   1.87 -0.98  0.95 -0.15
      id_3  -0.10  0.41  0.14  1.45
F     id_1   0.76  0.12  0.44  0.33
      id_2   1.49 -0.21  0.31 -0.85
      id_3  -2.55  0.65  0.86 -0.74

In [50]:
# 당연히 cidx1과 2는 행인덱스가 아니기 때문에 에러
df6 = df4.swaplevel("Cidx1", "Cidx2", 0)
df6

KeyError: 'Level Cidx1 not found'

## 다중 인덱스가 있는 경우의 정렬

다중 인덱스가 있는 데이터프레임을 `sort_index`로 정렬할 때는 `level` 인수를 사용하여 어떤 인덱스를 기준으로 정렬하는지 알려주어야 한다.

In [51]:
df5

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx2 Ridx1                        
id_1  M      1.76  0.40  0.98  2.24
id_2  M      1.87 -0.98  0.95 -0.15
id_3  M     -0.10  0.41  0.14  1.45
id_1  F      0.76  0.12  0.44  0.33
id_2  F      1.49 -0.21  0.31 -0.85
id_3  F     -2.55  0.65  0.86 -0.74
All   All    3.23  0.39  3.68  2.28

In [52]:
df5.sort_index?

Signature:
df5.sort_index(
    *,
    axis: 'Axis' = 0,
    level: 'IndexLabel' = None,
    ascending: 'bool | Sequence[bool]' = True,
    inplace: 'bool' = False,
    kind: 'SortKind' = 'quicksort',
    na_position: 'NaPosition' = 'last',
    sort_remaining: 'bool' = True,
    ignore_index: 'bool' = False,
    key: 'IndexKeyFunc' = None,
) -> 'DataFrame | None'
Docstring:
Sort object by labels (along an axis).

Returns a new DataFrame sorted by label if `inplace` argument is
``False``, otherwise updates the original DataFrame and returns None.

Parameters
----------
axis : {0 or 'index', 1 or 'columns'}, default 0
    The axis along which to sort.  The value 0 identifies the rows,
    and 1 identifies the columns.
level : int or level name or list of ints or list of level names
    If not None, sort on values in specified index level(s).
ascending : bool or list-like of bools, default True
    Sort ascending vs. descending. When the index is a MultiIndex the
    sort direction can be 

In [52]:
# 디폴트 axis=0 행인덱스, level = 인덱스 수준값 또는 라벨
df5.sort_index(level=0) # ridx2 기준

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx2 Ridx1                        
All   All    3.23  0.39  3.68  2.28
id_1  F      0.76  0.12  0.44  0.33
      M      1.76  0.40  0.98  2.24
id_2  F      1.49 -0.21  0.31 -0.85
      M      1.87 -0.98  0.95 -0.15
id_3  F     -2.55  0.65  0.86 -0.74
      M     -0.10  0.41  0.14  1.45

In [53]:
df5.sort_index(level=1) # ridx1 기준

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx2 Ridx1                        
All   All    3.23  0.39  3.68  2.28
id_1  F      0.76  0.12  0.44  0.33
id_2  F      1.49 -0.21  0.31 -0.85
id_3  F     -2.55  0.65  0.86 -0.74
id_1  M      1.76  0.40  0.98  2.24
id_2  M      1.87 -0.98  0.95 -0.15
id_3  M     -0.10  0.41  0.14  1.45

### 연습 문제
```
A 반 학생 5명과 B반 학생 5명의 국어, 영어, 수학 점수를 나타내는 데이터프레임을 다음과 같이 만든다.

1. "반", "번호", "국어", "영어", "수학" 을 열로 가지는 데이터프레임 `df_score3`을 만든다.

2. `df_score3`을 변형하여 1차 행 인덱스로 "반"을 2차 행 인덱스로 "번호"을 가지는 데이터프레임 `df_score4`을 만든다.

3. 데이터 프레임 `df_score4`에 각 학생의 평균을 나타내는 행을 오른쪽에 추가한다.

4. `df_score3`을 변형하여 행 인덱스로 "번호"를, 1차 열 인덱스로 "국어", "영어", "수학"을, 2차 열 인덱스로 "반"을 가지는 데이터프레임 `df_score5`을 만든다.

5. 데이터 프레임 `df_score5`에 각 반별 각 과목의 평균을 나타내는 행을 아래에 추가한다.

````

In [42]:
np.random.seed(0)    
class1 = np.array(list('AAAAABBBBB')).reshape(10, 1)
class1

array([['A'],
       ['A'],
       ['A'],
       ['A'],
       ['A'],
       ['B'],
       ['B'],
       ['B'],
       ['B'],
       ['B']], dtype='<U1')

In [39]:
score = np.random.randint(0,101,(10,3))
score

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58],
       [65, 39, 87],
       [46, 88, 81],
       [37, 25, 77],
       [72,  9, 20],
       [80, 69, 79]])

In [43]:
number = np.random.choice(range(1,6), 5, replace=False)
number

array([3, 1, 2, 4, 5])

In [44]:
# 1번
np.random.seed(0)                            
class1 = np.array(list('AAAAABBBBB')).reshape(10, 1)
score = np.random.randint(0,101,(10,3))
number = np.random.choice(range(1,6), 5, replace=False)
number = np.hstack([number, number]).reshape(10,1)
df_score3 = pd.DataFrame(np.hstack([class1,number, score]), columns=["반","번호","국어","영어","수학"])
df_score3          

반 번호  국어  영어  수학
0  A  4  44  47  64
1  A  2  67  67   9
2  A  5  83  21  36
3  A  3  87  70  88
4  A  1  88  12  58
5  B  4  65  39  87
6  B  2  46  88  81
7  B  5  37  25  77
8  B  3  72   9  20
9  B  1  80  69  79

In [50]:
df_score4 = df_score3.set_index(['반', '번호'])
df_score4

국어  영어  수학
반 번호            
A 4   44  47  64
  2   67  67   9
  5   83  21  36
  3   87  70  88
  1   88  12  58
B 4   65  39  87
  2   46  88  81
  5   37  25  77
  3   72   9  20
  1   80  69  79

In [53]:
# 3번 각 학생의 평균 계산
df_score4['평균'] = round(df_score4.mean(axis=1),1)
df_score4

TypeError: Could not convert ['444764' '67679' '832136' '877088' '881258' '653987' '468881' '372577'
 '72920' '806979'] to numeric

In [54]:
np.random.seed(0)    
class1 = np.array(list('AAAAABBBBB')).reshape(10, 1)
class1

array([['A'],
       ['A'],
       ['A'],
       ['A'],
       ['A'],
       ['B'],
       ['B'],
       ['B'],
       ['B'],
       ['B']], dtype='<U1')

In [55]:
score = np.random.randint(0,101,(10,3))
score

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58],
       [65, 39, 87],
       [46, 88, 81],
       [37, 25, 77],
       [72,  9, 20],
       [80, 69, 79]])

In [56]:
number = np.random.choice(range(1,6), 5, replace=False)
number

array([4, 2, 5, 3, 1])

In [57]:
number = np.hstack([number, number]).reshape(10, 1)
number

array([[4],
       [2],
       [5],
       [3],
       [1],
       [4],
       [2],
       [5],
       [3],
       [1]])

In [58]:
df_score3 = pd.DataFrame(np.hstack([class1,number, score]), columns=["반","번호","국어","영어","수학"])
df_score3

반 번호  국어  영어  수학
0  A  4  44  47  64
1  A  2  67  67   9
2  A  5  83  21  36
3  A  3  87  70  88
4  A  1  88  12  58
5  B  4  65  39  87
6  B  2  46  88  81
7  B  5  37  25  77
8  B  3  72   9  20
9  B  1  80  69  79

In [59]:
# 1번
np.random.seed(0)                            
class1 = np.array(list('AAAAABBBBB')).reshape(10, 1)
score = np.random.randint(0,101,(10,3))
number = np.random.choice(range(1,6), 5, replace=False)
number = np.hstack([number, number]).reshape(10,1)
df_score3 = pd.DataFrame(np.hstack([class1,number, score]), columns=["반","번호","국어","영어","수학"])
df_score3                                  

반 번호  국어  영어  수학
0  A  4  44  47  64
1  A  2  67  67   9
2  A  5  83  21  36
3  A  3  87  70  88
4  A  1  88  12  58
5  B  4  65  39  87
6  B  2  46  88  81
7  B  5  37  25  77
8  B  3  72   9  20
9  B  1  80  69  79

In [55]:
# 1번 for문으로 풀어보기

df_score3 = pd.DataFrame(columns=['반', '번호', '국어', '영어', '수학'])
df_score3

for i in range(5):
    df_score3.loc[i] = ['A', i+1] + list(np.random.randint(0, 101, size=3))
    df_score3.loc[i+5] = ['B', i+1] + list(np.random.randint(0, 101, size=3))
df_score3

반  번호  국어  영어  수학
0  A   1  29  19  19
5  B   1  14  39  32
1  A   2  65   9  57
6  B   2  32  31  74
2  A   3  23  35  75
7  B   3  55  28  34
3  A   4   0   0  36
8  B   4  53   5  38
4  A   5  17  79   4
9  B   5  42  58  31

In [56]:
# 2번 인덱스 설정
df_score4 = df_score3.set_index(['반', '번호'])
df_score4

국어  영어  수학
반 번호            
A 1   29  19  19
B 1   14  39  32
A 2   65   9  57
B 2   32  31  74
A 3   23  35  75
B 3   55  28  34
A 4    0   0  36
B 4   53   5  38
A 5   17  79   4
B 5   42  58  31

In [57]:
# 3번 각 학생의 평균 계산
df_score4['평균'] = round(df_score4.mean(axis=1),1)
df_score4

국어  영어  수학    평균
반 번호                  
A 1   29  19  19  22.3
B 1   14  39  32  28.3
A 2   65   9  57  43.7
B 2   32  31  74  45.7
A 3   23  35  75  44.3
B 3   55  28  34  39.0
A 4    0   0  36  12.0
B 4   53   5  38  32.0
A 5   17  79   4  33.3
B 5   42  58  31  43.7

In [58]:
# 4. `df_score3`을 변형하여 행 인덱스로 "번호"를, 1차 열 인덱스로 "국어", "영어", "수학"을, 
# 2차 열 인덱스로 "반"을 가지는 데이터프레임 `df_score5`을 만든다
# 행과 열 인덱스 변경  df_score3.set_index('번호').pivot(columns='반')
df_score3

반  번호  국어  영어  수학
0  A   1  29  19  19
5  B   1  14  39  32
1  A   2  65   9  57
6  B   2  32  31  74
2  A   3  23  35  75
7  B   3  55  28  34
3  A   4   0   0  36
8  B   4  53   5  38
4  A   5  17  79   4
9  B   5  42  58  31

In [59]:
df_score3.set_index(['번호','반'])

국어  영어  수학
번호 반            
1  A  29  19  19
   B  14  39  32
2  A  65   9  57
   B  32  31  74
3  A  23  35  75
   B  55  28  34
4  A   0   0  36
   B  53   5  38
5  A  17  79   4
   B  42  58  31

In [60]:
df_score5 = df_score3.set_index(['번호','반']).unstack()
df_score5

국어      영어      수학    
반    A   B   A   B   A   B
번호                        
1   29  14  19  39  19  32
2   65  32   9  31  57  74
3   23  55  35  28  75  34
4    0  53   0   5  36  38
5   17  42  79  58   4  31

In [61]:
# 각 반별 과목 평균 계산
df_score5.loc['평균'] = df_score5.mean(axis=0)
df_score5

국어          영어          수학      
반      A     B     A     B     A     B
번호                                    
1   29.0  14.0  19.0  39.0  19.0  32.0
2   65.0  32.0   9.0  31.0  57.0  74.0
3   23.0  55.0  35.0  28.0  75.0  34.0
4    0.0  53.0   0.0   5.0  36.0  38.0
5   17.0  42.0  79.0  58.0   4.0  31.0
평균  26.8  39.2  28.4  32.2  38.2  41.8

In [ ]:
df_score6 = df_score5.swaplevel("Ridx1", "Ridx2")